FROM mcr.microsoft.com/dotnet/core/sdk:3.1.100 AS build
WORKDIR /app
ARG sln_name
ARG host_workdir
ARG host_name
ARG publish_app_dir=${host_workdir}/bin/Debug/netcoreapp3.1
COPY ${publish_app_dir} .
ENTRYPOINT ["dotnet", "Surging.Hero.Gateway.dll"]