FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
ARG sln_name
ARG host_workdir
ARG host_name
ARG publish_app_dir=${host_workdir}/bin/Debug/net5.0
ENV TZ=Asia/Shanghai
ENV LANG C.UTF-8 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone 
COPY ${publish_app_dir} .
ENTRYPOINT ["dotnet", "Surging.Hero.Gateway.dll"]