FROM mcr.microsoft.com/dotnet/core/sdk:3.1.100 AS build
WORKDIR /src
ARG sln_name
ARG host_workdir
ARG host_name
COPY . .
RUN dotnet restore ${sln_name} && \
    dotnet build --no-restore ${sln_name}
WORKDIR ${host_workdir}    
RUN dotnet publish --no-restore -o /app
WORKDIR /app
ENTRYPOINT ["dotnet", "Surging.Hero.OrganizationHost.dll"]